version: "3.7"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
    command: npm run setup

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
    command: json-server data.json --host 0.0.0.0